;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        hungry-delete-backward
        hungry-delete-forward
        markdown-outdent-or-delete
        my-delete-word
        simple-emacs/backward-delete-word
        simple-emacs/delete-line
        simple-emacs/delete-word
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-describe-variable
        describe-key
        helm-M-x
        undo-tree-visualize
        ))
